/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package Reg.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Billing1 service. Represents a row in the &quot;Yash_Billing1&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>Reg.service.model.impl.Billing1ModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>Reg.service.model.impl.Billing1Impl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Billing1
 * @generated
 */
@ProviderType
public interface Billing1Model extends BaseModel<Billing1> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a billing1 model instance should use the {@link Billing1} interface instead.
	 */

	/**
	 * Returns the primary key of this billing1.
	 *
	 * @return the primary key of this billing1
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this billing1.
	 *
	 * @param primaryKey the primary key of this billing1
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this billing1.
	 *
	 * @return the uuid of this billing1
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this billing1.
	 *
	 * @param uuid the uuid of this billing1
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the billing address ID of this billing1.
	 *
	 * @return the billing address ID of this billing1
	 */
	public long getBillingAddressId();

	/**
	 * Sets the billing address ID of this billing1.
	 *
	 * @param billingAddressId the billing address ID of this billing1
	 */
	public void setBillingAddressId(long billingAddressId);

	/**
	 * Returns the user ID of this billing1.
	 *
	 * @return the user ID of this billing1
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this billing1.
	 *
	 * @param userId the user ID of this billing1
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this billing1.
	 *
	 * @return the user uuid of this billing1
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this billing1.
	 *
	 * @param userUuid the user uuid of this billing1
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the address of this billing1.
	 *
	 * @return the address of this billing1
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this billing1.
	 *
	 * @param address the address of this billing1
	 */
	public void setAddress(String address);

	/**
	 * Returns the address2 of this billing1.
	 *
	 * @return the address2 of this billing1
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this billing1.
	 *
	 * @param address2 the address2 of this billing1
	 */
	public void setAddress2(String address2);

	/**
	 * Returns the city of this billing1.
	 *
	 * @return the city of this billing1
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this billing1.
	 *
	 * @param city the city of this billing1
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this billing1.
	 *
	 * @return the state of this billing1
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this billing1.
	 *
	 * @param state the state of this billing1
	 */
	public void setState(String state);

	/**
	 * Returns the zip of this billing1.
	 *
	 * @return the zip of this billing1
	 */
	@AutoEscape
	public String getZip();

	/**
	 * Sets the zip of this billing1.
	 *
	 * @param zip the zip of this billing1
	 */
	public void setZip(String zip);

	@Override
	public Billing1 cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}