/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package Reg.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Contacts1 service. Represents a row in the &quot;Yash_Contacts1&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>Reg.service.model.impl.Contacts1ModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>Reg.service.model.impl.Contacts1Impl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Contacts1
 * @generated
 */
@ProviderType
public interface Contacts1Model extends BaseModel<Contacts1> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contacts1 model instance should use the {@link Contacts1} interface instead.
	 */

	/**
	 * Returns the primary key of this contacts1.
	 *
	 * @return the primary key of this contacts1
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contacts1.
	 *
	 * @param primaryKey the primary key of this contacts1
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this contacts1.
	 *
	 * @return the uuid of this contacts1
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this contacts1.
	 *
	 * @param uuid the uuid of this contacts1
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the phone ID of this contacts1.
	 *
	 * @return the phone ID of this contacts1
	 */
	public long getPhoneId();

	/**
	 * Sets the phone ID of this contacts1.
	 *
	 * @param phoneId the phone ID of this contacts1
	 */
	public void setPhoneId(long phoneId);

	/**
	 * Returns the user ID of this contacts1.
	 *
	 * @return the user ID of this contacts1
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this contacts1.
	 *
	 * @param userId the user ID of this contacts1
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this contacts1.
	 *
	 * @return the user uuid of this contacts1
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this contacts1.
	 *
	 * @param userUuid the user uuid of this contacts1
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the home phone of this contacts1.
	 *
	 * @return the home phone of this contacts1
	 */
	@AutoEscape
	public String getHomePhone();

	/**
	 * Sets the home phone of this contacts1.
	 *
	 * @param homePhone the home phone of this contacts1
	 */
	public void setHomePhone(String homePhone);

	/**
	 * Returns the mobile phone of this contacts1.
	 *
	 * @return the mobile phone of this contacts1
	 */
	@AutoEscape
	public String getMobilePhone();

	/**
	 * Sets the mobile phone of this contacts1.
	 *
	 * @param mobilePhone the mobile phone of this contacts1
	 */
	public void setMobilePhone(String mobilePhone);

	@Override
	public Contacts1 cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}