/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package Reg.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Student1 service. Represents a row in the &quot;Yash_Student1&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>Reg.service.model.impl.Student1ModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>Reg.service.model.impl.Student1Impl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Student1
 * @generated
 */
@ProviderType
public interface Student1Model extends BaseModel<Student1> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student1 model instance should use the {@link Student1} interface instead.
	 */

	/**
	 * Returns the primary key of this student1.
	 *
	 * @return the primary key of this student1
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student1.
	 *
	 * @param primaryKey the primary key of this student1
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this student1.
	 *
	 * @return the uuid of this student1
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this student1.
	 *
	 * @param uuid the uuid of this student1
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the user ID of this student1.
	 *
	 * @return the user ID of this student1
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this student1.
	 *
	 * @param userId the user ID of this student1
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this student1.
	 *
	 * @return the user uuid of this student1
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this student1.
	 *
	 * @param userUuid the user uuid of this student1
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the first name of this student1.
	 *
	 * @return the first name of this student1
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this student1.
	 *
	 * @param firstName the first name of this student1
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this student1.
	 *
	 * @return the last name of this student1
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this student1.
	 *
	 * @param lastName the last name of this student1
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the email address of this student1.
	 *
	 * @return the email address of this student1
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this student1.
	 *
	 * @param emailAddress the email address of this student1
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the username of this student1.
	 *
	 * @return the username of this student1
	 */
	@AutoEscape
	public String getUsername();

	/**
	 * Sets the username of this student1.
	 *
	 * @param username the username of this student1
	 */
	public void setUsername(String username);

	/**
	 * Returns the male of this student1.
	 *
	 * @return the male of this student1
	 */
	public boolean getMale();

	/**
	 * Returns <code>true</code> if this student1 is male.
	 *
	 * @return <code>true</code> if this student1 is male; <code>false</code> otherwise
	 */
	public boolean isMale();

	/**
	 * Sets whether this student1 is male.
	 *
	 * @param male the male of this student1
	 */
	public void setMale(boolean male);

	/**
	 * Returns the birthday month of this student1.
	 *
	 * @return the birthday month of this student1
	 */
	public int getBirthdayMonth();

	/**
	 * Sets the birthday month of this student1.
	 *
	 * @param birthdayMonth the birthday month of this student1
	 */
	public void setBirthdayMonth(int birthdayMonth);

	/**
	 * Returns the birthday day of this student1.
	 *
	 * @return the birthday day of this student1
	 */
	public int getBirthdayDay();

	/**
	 * Sets the birthday day of this student1.
	 *
	 * @param birthdayDay the birthday day of this student1
	 */
	public void setBirthdayDay(int birthdayDay);

	/**
	 * Returns the birthday year of this student1.
	 *
	 * @return the birthday year of this student1
	 */
	public int getBirthdayYear();

	/**
	 * Sets the birthday year of this student1.
	 *
	 * @param birthdayYear the birthday year of this student1
	 */
	public void setBirthdayYear(int birthdayYear);

	/**
	 * Returns the password1 of this student1.
	 *
	 * @return the password1 of this student1
	 */
	@AutoEscape
	public String getPassword1();

	/**
	 * Sets the password1 of this student1.
	 *
	 * @param password1 the password1 of this student1
	 */
	public void setPassword1(String password1);

	/**
	 * Returns the password2 of this student1.
	 *
	 * @return the password2 of this student1
	 */
	@AutoEscape
	public String getPassword2();

	/**
	 * Sets the password2 of this student1.
	 *
	 * @param password2 the password2 of this student1
	 */
	public void setPassword2(String password2);

	/**
	 * Returns the security question of this student1.
	 *
	 * @return the security question of this student1
	 */
	@AutoEscape
	public String getSecurityQuestion();

	/**
	 * Sets the security question of this student1.
	 *
	 * @param securityQuestion the security question of this student1
	 */
	public void setSecurityQuestion(String securityQuestion);

	/**
	 * Returns the security answer of this student1.
	 *
	 * @return the security answer of this student1
	 */
	@AutoEscape
	public String getSecurityAnswer();

	/**
	 * Sets the security answer of this student1.
	 *
	 * @param securityAnswer the security answer of this student1
	 */
	public void setSecurityAnswer(String securityAnswer);

	/**
	 * Returns the accepted terms of use of this student1.
	 *
	 * @return the accepted terms of use of this student1
	 */
	public boolean getAcceptedTermsOfUse();

	/**
	 * Returns <code>true</code> if this student1 is accepted terms of use.
	 *
	 * @return <code>true</code> if this student1 is accepted terms of use; <code>false</code> otherwise
	 */
	public boolean isAcceptedTermsOfUse();

	/**
	 * Sets whether this student1 is accepted terms of use.
	 *
	 * @param acceptedTermsOfUse the accepted terms of use of this student1
	 */
	public void setAcceptedTermsOfUse(boolean acceptedTermsOfUse);

	/**
	 * Returns the event date of this student1.
	 *
	 * @return the event date of this student1
	 */
	public Date getEventDate();

	/**
	 * Sets the event date of this student1.
	 *
	 * @param eventDate the event date of this student1
	 */
	public void setEventDate(Date eventDate);

	/**
	 * Returns the event type of this student1.
	 *
	 * @return the event type of this student1
	 */
	@AutoEscape
	public String getEventType();

	/**
	 * Sets the event type of this student1.
	 *
	 * @param eventType the event type of this student1
	 */
	public void setEventType(String eventType);

	/**
	 * Returns the ip address of this student1.
	 *
	 * @return the ip address of this student1
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this student1.
	 *
	 * @param ipAddress the ip address of this student1
	 */
	public void setIpAddress(String ipAddress);

	@Override
	public Student1 cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}